algoritmo "Valor maximo"

var

   contador, num, i, maior: inteiro

inicio

  escreva ("Digite a quantidade que sera pedido: ")
      leia(i)
      para contador <- 1 ate i faca
          escreval ("Informe o numero: ")
          leia (num)
          se num > maior entao
             maior <- num
          fimse
      fimpara

      escreval ( "o maior e: ",  maior )

          


fimalgoritmo
