algoritmo "Valor maximo"

var

   contador, num, soma, i: inteiro
   media: real


inicio

      soma <- 0
  escreva ("Digite a quantidade que sera pedido: ")
      leia(i)
      para contador <- 1 ate i faca
          escreval ("Informe o numero: ")
          leia (num)
          soma <- soma + num
      fimpara

          media <- soma/i
         escreval ( "a media e: ", media )
          


      
fimalgoritmo
